name: Android App Release Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*.prod'

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, '.prod')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v4
      #   with:
      #     run_install: false

      # - name: Setup node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version-file: package.json
      #     cache: 'pnpm'

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # - name: Setup yarn
      #   if: ${{ env.ACT }}
      #   run: npm install -g yarn

      # - name: Setup Expo
      #   uses: expo/expo-github-action@v8
      #   with:
      #     eas-version: latest
      #     token: ${{ secrets.EXPO_TOKEN }}

      # - name: Install dependencies
      #   run: pnpm install --frozen-lockfile

      # - name: Build Android app
      #   run: |
      #     cd ./apps/mobile
      #     eas build --local --platform=android --output=${{ github.workspace }}/app.prod.aab --no-wait

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/app.prod.aab
          name: Release ${{ github.ref_name }}
