name: Flutter CI/CD

on:
  push:
    branches:
      - development  # Run workflow on push to the main branch
  pull_request:
    branches:
      - development  # Run workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'

      - name: Install dependencies
        run: flutter pub get

#      - name: Run tests
#        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: v1.0.${{ github.run_number }}  # Use the same tag created above
            release_name: Release v1.0.${{ github.run_number }}
            draft: false
            prerelease: false
